### ISSUE TITLE
cross compile  libvdpau-sunxi to report error.how to solve this problem?

### ISSUE THREAD

**Issue by zhang007z** [linux-sunxi/libvdpau-sunxi#33]
my pc OS is ubuntu 14.04 version at X86 64bit.
I cross compile your  libvdpau-sunxi project,but this have reporte error as follow:
//------------------------------------------------------------------------------------------------------------//
root@ubuntu:~/gstreamer-0.10.36/vdpau_sunxi/libvdpau-sunxi# make
arm-linux-gnueabihf-gcc -shared -Wl,-soname,libvdpau_sunxi.so.1  device.o presentation_queue.o surface_output.o surface_video.o surface_bitmap.o video_mixer.o decoder.o handles.o ve.o h264.o mpeg12.o mpeg4.o rgba.o tiled_yuv.o -lrt -lm -lX11 -lpthread -o libvdpau_sunxi.so.1
/usr/local/gcc-linaro-arm-linux-gnueabihf-4.8-2013.10_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.8.2/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lX11
collect2: error: ld returned 1 exit status
make: *** [libvdpau_sunxi.so.1] Error 1
//------------------------------------------------------------------------------------------------------------//
first , I modify my crosscompile tools is "gcc-linaro-arm-linux-gnueabihf-4.8-2013.10_linux".
at above this hint me ,it say "arm-linux-gnueabihf/bin/ld: cannot find -lX11" , I think this problem need arm  X11 library version. I want to know wheather this  X11 version need compile  for arm or not.
My  X11 library locate  "/usr/lib/x86_64-linux-gnu/libX11.so". I think X11 version is  wrong. 

you have any idea for me. thank you for helping me.

**Comment by rellla** [comment]
"I think this problem need arm X11 library version"

You need to install the armhf version of the X11 library.

**Comment by zhang007z** [comment]
thank you for supporting advise.
