### ISSUE TITLE
rgba.c rgba_put_bits_native optimization incorrect

### ISSUE THREAD

**Issue by daym** [linux-sunxi/libvdpau-sunxi#36]
The line "if (0 == d_rect.x0 && rgba->width == d_rect.x1 && source_pitches[0] ==d_rect.x1)" in rgba.c to test for full-width requests is incorrect.

While vdpau documentation is kinda lacking, at least mplayer does pitch = width * Byte_per_pixel . This shows that the pitch value is probably meant to be in Byte. Therefore, the comparison should probably read ..."&& source_pitches[0] == d_rect.x1 * 4)". 

Printing the values also showed the "pitch == 4 * (x1 - x0)" to be the case for smaller rectangles.

Unfortunately I don't know any application that uses this to put full screen images on screen. If anyone knows one, please test it and print d_rect.x1 and source_pitches[0] and see whether they roughly match.

**Comment by jemk** [comment]
Your are right, the source_pitches are in byte, otherwise the memcpy in the else block would not work.
And, yes, vdpau documentation is nearly useless sometimes...
