### ISSUE TITLE
libvdpau-sunxi do not work on my Allwinner A33 device

### ISSUE THREAD

**Issue by Icenowy** [linux-sunxi/libvdpau-sunxi#38]
When I am trying to use libvdpau-sunxi on my Allwinner A33 device(with the offical SDK's kernel, lichee/linux-3.4), I got such errors:

[vdpau] Failed creating VDPAU decoder: The system does not have enough resources to complete the requested operation at this time.
[vdpau] Failed creating VDPAU decoder: The system does not have enough resources to complete the requested operation at this time.
The selected video_out device is incompatible with this codec.
Try appending the scale filter to your filter list,
e.g. -vf spp,scale instead of -vf spp.
[vdpau] Failed creating VDPAU decoder: The system does not have enough resources to complete the requested operation at this time.
[vdpau] Failed creating VDPAU decoder: The system does not have enough resources to complete the requested operation at this time.
The selected video_out device is incompatible with this codec.
Try appending the scale filter to your filter list,
e.g. -vf spp,scale instead of -vf spp.
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12
Unexpected decoder output format Planar YV12

/dev/cedar_dev and /dev/disp are all present on the kernel.

**Comment by Icenowy** [comment]
My X11 driver is xf86-video-fbturbo (but I disabled g2d support, because a33 has no g2d)
When I tried to use -vo x11 instead of -vo vdpau, the video is present, but it seems that it's software decoded, as the CPU usage of mplayer is higher than 80% and mplayer told me that "You system is too SLOW to play this"

**Comment by rellla** [comment]
libvdpau-sunxi is supposed to work only on A10/A20 devices. A33 support is neither implemented nor planned.
rellla

**Comment by Icenowy** [comment]
How can I satisfy it? 
In addition, is the ioctl interface between different Allwinner SoCs the same?

**Comment by rellla** [comment]
i don't know. look into the kernel sources of A33 and A20. other than video engine, i don't know what the differences in display engine are.
