### ISSUE TITLE
H265 and 4K Support for Allwinner H3

### ISSUE THREAD

**Issue by SamuelBrucksch** [linux-sunxi/libvdpau-sunxi#39]
Hi,

i did not test yet, if the driver works with the H3 as well, as my board is still on its way. But as it is a SoC of the sunxi family as well i hope it will work.

Will you add h265 and 4k support as well (or maybe will 4k work already)? The H3 seems to have hardware acceleration for that, but if no driver is available that chip really is useless.

Thanks

Samuel

**Comment by rellla** [comment]
Atm there is no support for H3. VE engine seems to be relatively equal, but H3 uses a complete different display engine. Support for h265 is another story...

**Comment by SamuelBrucksch** [comment]
Ok so there is no way to use HW accelerated video on the H3 yet in linux. Do you plan to add H3 support?

**Comment by oliv3r** [comment]
I guess at first, we'd want to ideally see it added to https://github.com/allwinner-zh/media-codec/tree/master/sunxi-cedarx/SOURCE

of course if the h265 portion ends up being in the 'lib' part, it'll take a few years worth of RE-ing.

**Comment by jemk** [comment]
@oliv3r closed this a bit fast, I've been working on it already.
Both should be possible with the h3-dev branch. Since the kernel interfaces changed, but don't provide any version information, this branch currently only works on H3.
H3's new display driver is completely undocumented and doesn't seem to provide many features, so there won't be OSD support and the video layer is always on top.

**Comment by SamuelBrucksch** [comment]
Just testet h264 and it seems to work, however h265 breaks the build. I needed to remove h265.c in Makefile and these two parts in decoder.c to get it to work:
https://github.com/linux-sunxi/l ... v/decoder.c#L73-L78
https://github.com/linux-sunxi/l ... decoder.c#L205-L211

After that it works with mplayer, but only in fullscreen. When not in fullscreen the video looks pretty strange.

**Comment by rellla** [comment]
which libvdpau headers do you build against?

**Comment by SamuelBrucksch** [comment]
Thats actually a quite good remark, i didnt check it. i just used the ones, that are in the ubuntu 15.04 apt repository. Just had a look it is 0.9-lubuntu0.1. Latest seems to be 1.1.1, will check later if i can compile with h265 support hen.

**Comment by jemk** [comment]
You'll need libvdpau >= 1.1, h265 was added in 1.0 but had a bug that got fixed in 1.1

The scaling could be a problem with disp2, desktop and video must not share a channel for scaling to work correctly, but video has to use channel 0. So if your desktop uses channel 0 too it wont work. At least thats what I've guessed based on experiments. To be sure Allwinner would have to release some documentation.

**Comment by SamuelBrucksch** [comment]
Tried with 1.1 and compiling worked, didnt try it though...

Is it somehow possible to modify this driver for use without X11 like on the rapsi, where i can start the video from console?

**Comment by jemk** [comment]
Vdpau requires X11. This driver could theoretically work without X, but vdpau enforces it.

**Comment by SamuelBrucksch** [comment]
Thanks for all the information. Is there an easy way to test the driver without libvdpau/x11? How would i do it.

**Comment by mosterta** [comment]
Vdpau itself does not need X, only the current implementation of libvdpau. I have a libvdpau without X. But of course the application which uses libvdpau must be aware of it. 

BR
Martin

Am 1. Dezember 2015 19:22:25 MEZ, schrieb Jens Kuske <notifications@github.com>:
>Vdpau requires X11. This driver could theoretically work without X, but
>vdpau enforces it.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/linux-sunxi/libvdpau-sunxi/issues/39#issuecomment-161053867

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mittorn** [comment]
I think, it is very easy to modify mplayer/mpv to make vdpau work without X.

**Comment by SamuelBrucksch** [comment]
Any instructions/hints?
