### ISSUE TITLE
Pink screen with artifacts on H3 - 2 GB RAM

### ISSUE THREAD

**Issue by avafinger** [linux-sunxi/libvdpau-sunxi#42]
I get a pink screen with white artifacts displayed on screen. The board is OPI-Plus 2. If you don't have one available and this is possibly a memory mapping issue i can compile the changes and give feedback.

**Comment by jemk** [comment]
Have you already tried with the latest commit (743bdfbc81832dc7317b5a79b4d90dcfe1025ff8)?

**Comment by avafinger** [comment]
sorry, did not see that, will try and get back.

**Comment by avafinger** [comment]
Fixed, thank you and forgive me.

**Comment by jemk** [comment]
No problem, thanks for testing it. I don't have newer devices with 2GB.
