### ISSUE TITLE
h264 decoding errors

### ISSUE THREAD

**Issue by mosterta** [linux-sunxi/libvdpau-sunxi#44]
When watching the H264 video from 
http://media.ndr.de/progressive/2016/0228/TV-20160228-2302-5700.hq.mp4
Macroblock decoding errors can be seen.

**Comment by jemk** [comment]
Which SoC and software are you testing this with?
On my A20 vdpau decoded this video bit-identical to what `ffmpeg -i TV-20160228-2302-5700.hq.mp4 -c:v rawvideo -pix_fmt yuv420p data.yuv` decodes by software.

**Comment by mosterta** [comment]
sorry, my fault. I didn't use the last version of the code. I can decode it correctly now.
