### ISSUE TITLE
Sluggish image and garbled color blocks on screen when use 3.4.110 kernel.

### ISSUE THREAD

**Issue by fisherguy** [linux-sunxi/libvdpau-sunxi#45]
I tried this on with kernel 3.4.9 which works OK on H3 based OrangePi PC, but recently I installed kernel 3.4.110 based Armbian 5.05 it stops working. I get sluggish image and garbled color blocks on screen when playing a 720P video, and 1080P video will not play. I already got Mali400 working btw. Any fix?

**Comment by WereCatf** [comment]
@fisherguy Did you just install the kernel from Armbian, or are you trying the whole Armbian - image? We install VDPAU and everything already by default on the Orange Pi - images and they work fine on my OPi PC.

**Comment by fisherguy** [comment]
I tried fresh install of Armbian 5.05. I installed libvdpau-sunxi and MPV as I did on Debian 8 kernel 3.4.39, but only 3.4.39 works.

**Comment by WereCatf** [comment]
@fisherguy Why didn't you just use the desktop-image? It already includes all this stuff, including fbturbo, libvdpau-sunxi, mpv 0.16 and even setting mpv to use VDPAU by default, you know.

If you insist on doing it all yourself you need remember to edit boot.cmd and remove the part that disables memory-reservations.

**Comment by fisherguy** [comment]
I already said I tried 5.05 but the preinstalled MPV not working. Have you tried HD video?

**Comment by fisherguy** [comment]
Why should I edit boot.cmd and remove the part that disables memory-reservations?

**Comment by WereCatf** [comment]
Yes, 1080p H.264 and HEVC play just fine on my OPi PC. I have only built my Armbian from the sources, I'll check if Igor messed up the images, will take a few minutes.

**Comment by fisherguy** [comment]
Care to share your build? Btw is it using LXDE desktop?

**Comment by WereCatf** [comment]
I just tested, the image works absolutely fine as-is. Either you didn't use the desktop-image ( http://mirror.igorpecovnik.com/Armbian_5.05_Orangepih3_Debian_jessie_3.4.110_desktop.zip ) or you have messed something else up.

**Comment by rellla** [comment]
seems closeable?
