### ISSUE TITLE
How does h264 use?

### ISSUE THREAD

**Issue by aleksandrpestr** [linux-sunxi/libvdpau-sunxi#46]
I've compiled this library. I haven't found examples how I can use it.
Can you help me?
I am trying to make a simple program for coding and decoding video frames.

**Comment by WereCatf** [comment]
You don't use libvdpau-sunxi directly, you use libvdpau. If you set the environment-variable right (`export VDPAU_DRIVER=sunxi`) libvdpau will then use libvdpau-sunxi as its back-end.

Google for examples on how to use libvdpau instead.

PS. VDPAU doesn't do encoding, only decoding -- I take "program for coding" to mean you also want your app to encode video, but then you need to use something else for that.

**Comment by aleksandrpestr** [comment]
Thanks a lot!
