### ISSUE TITLE
ffplay doesn't work with libvdpau-sunxi

### ISSUE THREAD

**Issue by slapin** [linux-sunxi/libvdpau-sunxi#51]
I'm using armbian.
When I recompile ffmpeg from deb-multimedia to support vaapi and vdpau,
and then try to use vdpau, I get crashes with git master, and with version included in armbian.
ffmpeg version is 2.6.9.

Is there something I can do to make it work or to provide better bug report?
```
$ export VDPAU_OSD=1
$ export VDPAU_DRIVER=sunxi
$ ffplay -codec:v mpegvideo_vdpau VIDEO_TS/VTS_01_1.VOB 
ffplay version 2.6.9 Copyright (c) 2003-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --cc='ccache cc' --enable-shared --enable-libmp3lame --enable-gpl --enable-nonfree --enable-libvorbis --enable-pthreads --enable-libfaac --enable-libxvid --enable-postproc --enable-x11grab --enable-libgsm --enable-libtheora --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-libspeex --enable-nonfree --disable-stripping --enable-libvpx --enable-libschroedinger --disable-encoder=libschroedinger --enable-version3 --enable-libopenjpeg --enable-librtmp --enable-avfilter --enable-libfreetype --enable-libvo-aacenc --disable-decoder=amrnb --enable-libvo-amrwbenc --enable-libaacplus --libdir=/usr/lib/arm-linux-gnueabihf --disable-vda --enable-libbluray --enable-libcdio --enable-gnutls --enable-frei0r --enable-openssl --enable-libass --enable-libopus --enable-fontconfig --enable-libpulse --disable-mips32r2 --disable-mipsdspr1 --disable-mipsdspr2 --enable-libvidstab --enable-libzvbi --enable-avresample --disable-htmlpages --disable-podpages --enable-libutvideo --enable-libfdk-aac --enable-libx265 --enable-vdpau --enable-vaapi --enable-hwaccel=h263_vaapi --enable-hwaccel=h263_vdpau --enable-hwaccel=h264_vaapi --enable-hwaccel=h264_vdpau --enable-hwaccel=mpeg1_vdpau --enable-hwaccel=mpeg2_vaapi --enable-hwaccel=mpeg2_vdpau --enable-hwaccel=mpeg4_vaapi --enable-hwaccel=mpeg4_vdpau --enable-hwaccel=wmv3_vaapi --enable-hwaccel=wmv3_vdpau --enable-libiec61883 --enable-libdc1394 --disable-altivec --shlibdir=/usr/lib/arm-linux-gnueabihf
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mpeg, from 'VIDEO_TS/VTS_01_1.VOB': 0KB sq=    0B f=0/0   
  Duration: 00:03:44.38, start: 0.280633, bitrate: 38276 kb/s
    Stream #0:0[0x1bf]: Data: dvd_nav_packet
    Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv), 720x480 [SAR 8:9 DAR 4:3], max. 8500 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:2[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 256 kb/s
    Stream #0:3[0x81]: Audio: ac3, 48000 Hz, stereo, fltp, 256 kb/s
    Stream #0:4[0x82]: Audio: ac3, 48000 Hz, stereo, fltp, 256 kb/s
    Stream #0:5[0x20]: Subtitle: dvd_subtitle
Segmentation faultn fd=   0 aq=  307KB vq= 3948KB sq=    0B f=0/0   
```

**Comment by slapin** [comment]
need to mention, that mpv bundled with armbian works fine, but nothing else.

**Comment by jemk** [comment]
ffplay doesn't work with any vdpau, it even crashes on x86 with these parameters.
ffmpeg (library) supports vdpau, but ffplay doesn't as far as I know. (https://ffmpeg.org/pipermail/ffmpeg-user/2012-July/008121.html)
mpv, mplayer, vlc are all working pretty well with every vdpau implementation, including vdpau-sunxi, gstreamer is said to be working too, but I haven't tried it yet.

**Comment by slapin** [comment]
Does that mean that current firefox (the one you get checking-out using hg)
(which uses ffmpeg) should work too?

**Comment by jemk** [comment]
I don't know, if it supports vdpau (and doesn't need any opengl interop features) it pobably could. 
But it looks like firefox doesn't support vdpau: https://bugzilla.mozilla.org/show_bug.cgi?id=1210729#c12

**Comment by slapin** [comment]
Both Firefox and Chromium do support vaapi (via Xv or when forced, as I
understand) and there are drivers
which support vdpau as vaapi backend, but this also looks like depend on Xv.
Chromium supports vaapi via patch and Firefox supports vaapi via
gstreamer1.0-vaapi or (newer versions)
via ffmpeg. The problem is I can't make vaapi-vdpau work :( as it expects
Xv to be working, and it doesn't
work on armbian for some reason...

**Comment by jemk** [comment]
I can't help your there, none of the things you mentioned has anything to do with vdpau.
If for any reason the vaapi driver has problems with vdpau-sunxi we can try to fix it, but currently your problems seem to be way before even touching vdpau.
