### ISSUE TITLE
no XVIDEO support means no ffmpeg and no video in browser

### ISSUE THREAD

**Issue by slapin** [linux-sunxi/libvdpau-sunxi#52]
All current software uses Xv to detect hardware acceleration in vide decoding.
As Xv is not supported, all software (unless specially hacked) fallbacks to software
decoding. The only other way to provide hardware acceleration is via DRM, but
it is not supported either. So currently people are left to use software decoding
unless using specially-crafted mpv. I think this should change some time. Any plans?

**Comment by rzk** [comment]
> All current software

define "current software"? VLC can use vdpau/vaapi, smplayer can use mpv as a backend. No idea for Kodi though. ffmpeg IIRC had x264vdpau decode module that you can use. same might go for gstreamer.

Also you seem to fail to understand what Xv is. We already have Xv support in https://github.com/ssvb/xf86-video-fbturbo/blob/master/src/sunxi_video.c if you really need it (hint: you actually don't).

> The only other way

only other way is vaapi, which is used by Intel

>  So currently people are left to use software decoding unless using specially-crafted mpv.

there is no "specially-crafted" mpv, we pass standard flags to mpv to direct it to use vdpau. I've used standard mpv from ArchLinux and Ubuntu and they both did good. You use exactly same flags to have video decoding acceleration on AMD video cards on x86.

**Comment by slapin** [comment]
Thanks a lot for clearing this out.
