### ISSUE TITLE
Can't compile - decode.o error

### ISSUE THREAD

**Issue by palandlom** [linux-sunxi/libvdpau-sunxi#53]
During compilation I get that error:

root@wf-laptop:/home/_ins/libvdpau-sunxi-git/libvdpau-sunxi# make
cc -MD -MP -MQ decoder.o -fpic -fvisibility=hidden -Wall -O3 -I/usr/include/pixman-1  -c decoder.c -o decoder.o
decoder.c: In function ‘vdp_decoder_create’:
decoder.c:73:7: error: ‘VDP_DECODER_PROFILE_HEVC_MAIN’ undeclared (first use in this function)
case VDP_DECODER_PROFILE_HEVC_MAIN:
       ^
decoder.c:73:7: note: each undeclared identifier is reported only once for each function it appears in
decoder.c: In function ‘vdp_decoder_query_capabilities’:
decoder.c:205:7: error: ‘VDP_DECODER_PROFILE_HEVC_MAIN’ undeclared (first use in this function)
 case VDP_DECODER_PROFILE_HEVC_MAIN:
       ^
decoder.c:206:16: error: ‘VDP_DECODER_LEVEL_HEVC_5’ undeclared (first use in this function)
   *max_level = VDP_DECODER_LEVEL_HEVC_5;
                ^
Makefile:47: recipe for target 'decoder.o' failed
make: *** [decoder.o] Error 1

Platform: Banana Pi PRO + linux mate Linux wf-laptop 3.4.103+ #1 SMP PREEMPT Tue Mar 10 19:55:05 CST 2015 armv7l armv7l armv7l GNU/Linux

**Comment by jemk** [comment]
Let me quote the readme:

Requirements:
    libvdpau >= 1.1
