### ISSUE TITLE
Can't get smooth video / out of sync (A64)

### ISSUE THREAD

**Issue by avafinger** [linux-sunxi/libvdpau-sunxi#56]
I am trying to play big_buck_bunny_1080p_H264_AAC_25fps_7200K.MP4 but video playback is sluggish and sound out of sync.
There seems to be a ion memory problem, so i think.
Can you see where i should look for to try to fix this?

**Here is the kernel error:**
[  343.875244] ycy begin open cedar-ve
[  343.875332] ycy open cedar-ve the ref_count is 0
[  343.875337] ycy end open cedar-ve
[  343.989003] sunxi_ion_ioctl(65) err: cmd not support!
[  344.061085] [DISP] disp_ioctl,line:1558:para err in disp_ioctl, cmd = 0x0,screen id = 65536
[  344.160045] alloc_contig_range test_pages_isolated(7dcde, 7dd5e) failed
[  350.620375] alloc_contig_range test_pages_isolated(7e88c, 7eb89) failed
[  356.889365] now do nothing 
[  356.889497] ycy begin release cedar-ve
[  356.889517] ycy release cedar-ve the ref_count is 0
[  496.033443] ycy begin open cedar-ve
[  496.033468] ycy open cedar-ve the ref_count is 0
[  496.033472] ycy end open cedar-ve
[  497.485334] sunxi_ion_ioctl(65) err: cmd not support!
[  497.566225] [DISP] disp_ioctl,line:1558:para err in disp_ioctl, cmd = 0x0,screen id = 65536
[  497.642521] alloc_contig_range test_pages_isolated(7d621, 7d91e) failed
[  497.691266] alloc_contig_range test_pages_isolated(7dd1c, 7e019) failed
[  497.832891] alloc_contig_range test_pages_isolated(7e019, 7e316) failed
[  501.801376] now do nothing 
[  501.801514] ycy begin release cedar-ve
[  501.801534] ycy release cedar-ve the ref_count is 0

> mplayer -vo vdpau -vc ffmpeg12vdpau,ffh264vdpau, big_buck_bunny_1080p_H264_AAC_25fps_7200K.MP4 
Creating config file: /root/.mplayer/config
MPlayer 1.2.1 (Debian), built with gcc-5.3.1 (C) 2000-2016 MPlayer Team
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.
Playing big_buck_bunny_1080p_H264_AAC_25fps_7200K.MP4.
libavformat version 56.40.101 (external)
libavformat file format detected.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f78e36608]Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (aac), -aid 0, -alang und
VIDEO:  [H264]  1920x1080  24bpp  25.000 fps  7254.9 kbps (885.6 kbyte/s)
Clip info:
 major_brand: mp42
 minor_version: 1
 compatible_brands: isommp423gp5
 creation_time: 2011-08-04 01:51:12
 title: big_buck_bunny_1080p_surround.avi_006.AVI.MP4
 artist: created with SUPER(C).v2011.bld.49
 encoder: eRightSoft
 comment: 09:51:32
Load subtitles in ./
[VDPAU SUNXI] VE version 0x1689 opened
[VDPAU SUNXI] OSD disabled!
==========================================================================
Forced video codec: ffmpeg12vdpau
Forced video codec: ffh264vdpau
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 56.60.100 (external)
Selected video codec: [ffh264vdpau] vfm: ffmpeg (FFmpeg H.264 (VDPAU))
==========================================================================
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
AUDIO: 44100 Hz, 2 ch, floatle, 96.1 kbit/3.40% (ratio: 12009->352800)
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))
==========================================================================
AO: [pulse] 44100Hz 2ch floatle (4 bytes per sample)
Starting playback...
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [vdpau] 1920x1080 => 1920x1080 H.264 VDPAU acceleration 
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [vdpau] 1920x1080 => 1920x1080 H.264 VDPAU acceleration 
A:   7.5 V:   7.5 A-V:  0.015 ct:  0.045   0/  0 25% 38%  3.5% 6 0 

Exiting... (Quit)
<

**Comment by avafinger** [comment]
Additional info, i had previously run without FBTURBO installed, i thought it would not improve anything, with FBTURBO the order of the errors changed a bit and there had very litle improvement, with FBTURBO i still get the errors, some clue?

```
[  716.883659] ycy begin open cedar-ve
[  716.883684] ycy open cedar-ve the ref_count is 0
[  716.883689] ycy end open cedar-ve
[  717.027370] [DISP] disp_ioctl,line:1558:para err in disp_ioctl, cmd = 0x0,screen id = 65536
[  717.030117] sunxi_ion_ioctl(65) err: cmd not support!
[  718.267360] now do nothing 
[  718.267441] ycy begin release cedar-ve
[  718.267453] ycy release cedar-ve the ref_count is 0
```


```
MPlayer 1.2.1 (Debian), built with gcc-5.3.1 (C) 2000-2016 MPlayer Team
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control
Playing big_buck_bunny_1080p_H264_AAC_25fps_7200K.MP4.
libavformat version 56.40.101 (external)
libavformat file format detected.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f80a71608]Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (aac), -aid 0, -alang und
VIDEO:  [H264]  1920x1080  24bpp  25.000 fps  7254.9 kbps (885.6 kbyte/s)
Clip info:
 major_brand: mp42
 minor_version: 1
 compatible_brands: isommp423gp5
 creation_time: 2011-08-04 01:51:12
 title: big_buck_bunny_1080p_surround.avi_006.AVI.MP4
 artist: created with SUPER(C).v2011.bld.49
 encoder: eRightSoft
 comment: 09:51:32
Load subtitles in ./
[VDPAU SUNXI] VE version 0x1689 opened
[VDPAU SUNXI] OSD disabled!
==========================================================================
Forced video codec: ffmpeg12vdpau
Forced video codec: ffh264vdpau
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 56.60.100 (external)
Selected video codec: [ffh264vdpau] vfm: ffmpeg (FFmpeg H.264 (VDPAU))
==========================================================================
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
AUDIO: 44100 Hz, 2 ch, floatle, 96.1 kbit/3.40% (ratio: 12009->352800)
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))
==========================================================================
AO: [pulse] 44100Hz 2ch floatle (4 bytes per sample)
Starting playback...
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [vdpau] 1920x1080 => 1920x1080 H.264 VDPAU acceleration 
[VDPAU SUNXI] sunxi_disp_open /dev/disp open OK
[VDPAU SUNXI] sunxi_disp2_open /dev/disp open OK
[VDPAU SUNXI] sunxi_disp2_open DISP_LAYER_SET_CONFIG
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [vdpau] 1920x1080 => 1920x1080 H.264 VDPAU acceleration 
A:  11.5 V:  11.4 A-V:  0.018 ct:  0.043   0/  0 38% 36%  4.2% 11 0 

Exiting... (Quit)

```

**Comment by rellla** [comment]
For me this seems to be a memory allocation error? 
libcedrus first tries to allocate memory via UMP (if defined), then it tries to use it's own allocator, and at last it tries to get it via ION. As some ion ioctl failed, it seems, UMP and VE also failed before. 
https://github.com/rellla/libcedrus/blob/master/cedrus.c#L65
Which ion ioctl causes that error? Which kernel do you use?

**Comment by avafinger** [comment]
Hi rella, thanks for your response.

* It is using ION mem manager, sunxi_ion_ioctl(65) err: cmd not support! is due to libcedrus asking ION_IOC_SUNXI_FLUSH_RANGE to detect the new memory allocation.
* Kernel is 3.10.105 (longsleep derived)
* someone is calling: [DISP] disp_ioctl,line:1558:para err in disp_ioctl, cmd = 0x0,screen id = 65536 with wrong parameters, i have no way to find out, it seems to start receiving this call after i setup xorg.conf, i was running without one.

At first, i had run without FBTURBO, so i suspected VDPAU SUNXI was calling some invalid DISP ioctl that generated the ion mem error. FBTURBO seems to make use of UMP / MALI calls and i don't have it either. Anyways i installed it to see what would happens. The order of the ioctl error just changed.

* Changed CMA to 192 MB that would supposed to fix the ion mem error, only reduced a bit, Android have cma=64 MB and if i recall correctly, on cubieboard was 128 / 192 MB, may i should go with 256 MB, but seems very high, well 64 bit anyway.

Can you see what would make ion to fail? and  how could i track down when libvdpau ask memory that fails?

Encoding (cedrus) works with ION mem manager without errors, maybe it does not ask for much memory.
Would you think installing libUMP in the same way we do on A20 would make such a difference? My understanding is that it is used by MALI.


X.Org X Server 1.18.4
Release Date: 2016-07-19
[    21.618] X Protocol Version 11, Revision 0
[    21.618] Build Operating System: Linux 4.4.0-45-generic aarch64 Ubuntu
[    21.618] Current Operating System: Linux nanopi-a64 3.10.105 #2 SMP PREEMPT Sun Apr 16 18:39:34 BRT 2017 aarch64
[    21.618] Kernel command line: console=tty0 console=ttyS0,115200n8 no_console_suspend disp.screen0_output_mode=1080p60 earlycon=uart,mmio32,0x01c28000 mac_addr=36:c9:e3:f1:b8:05 root=/dev/mmcblk0p2 ro rootwait
[    21.618] Build Date: 02 November 2016  10:05:28PM
[    21.618] xorg-server 2:1.18.4-0ubuntu0.2 (For technical support please see http://www.ubuntu.com/support) 
[    21.618] Current version of pixman: 0.33.6
[    21.618] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    21.618] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    21.620] (==) Log file: "/var/log/Xorg.0.log", Time: Sun Apr 16 17:24:38 2017
[    21.668] (==) Using config file: "/etc/X11/xorg.conf"
[    21.668] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    21.678] (==) ServerLayout "Default Layout"
[    21.678] (==) No screen section available. Using defaults.
[    21.678] (**) |-->Screen "Default Screen Section" (0)
[    21.678] (**) |   |-->Monitor "<default monitor>"
[    21.684] (==) No device specified for screen "Default Screen Section".
	Using the first device section listed.
[    21.684] (**) |   |-->Device "NanoPi A64"
[    21.684] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[    21.684] (**) Option "BlankTime" "0"
[    21.684] (**) Option "StandbyTime" "0"
[    21.684] (**) Option "SuspendTime" "0"
[    21.684] (**) Option "OffTime" "0"
[    21.684] (==) Automatically adding devices
[    21.684] (==) Automatically enabling devices
[    21.684] (==) Automatically adding GPU devices
[    21.684] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    21.697] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    21.697] 	Entry deleted from font path.
[    21.697] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    21.697] 	Entry deleted from font path.
[    21.697] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    21.697] 	Entry deleted from font path.
[    21.697] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    21.697] 	Entry deleted from font path.
[    21.697] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    21.697] 	Entry deleted from font path.
[    21.697] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    21.697] 	Entry deleted from font path.
[    21.697] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[    21.697] (==) ModulePath set to "/usr/lib/aarch64-linux-gnu/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[    21.697] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    21.698] (II) Loader magic: 0x5584175d80
[    21.698] (II) Module ABI versions:
[    21.698] 	X.Org ANSI C Emulation: 0.4
[    21.698] 	X.Org Video Driver: 20.0
[    21.698] 	X.Org XInput driver : 22.1
[    21.698] 	X.Org Server Extension : 9.0
[    21.701] (++) using VT number 7

[    21.701] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    21.701] (II) no primary bus or device found
[    21.701] (II) LoadModule: "glx"
[    21.788] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    21.869] (II) Module glx: vendor="X.Org Foundation"
[    21.869] 	compiled for 1.18.4, module version = 1.0.0
[    21.869] 	ABI class: X.Org Server Extension, version 9.0
[    21.869] (==) AIGLX enabled
[    21.871] (II) LoadModule: "fbturbo"
[    21.872] (II) Loading /usr/lib/xorg/modules/drivers/fbturbo_drv.so
[    21.936] (II) Module fbturbo: vendor="X.Org Foundation"
[    21.936] 	compiled for 1.18.4, module version = 0.5.1
[    21.936] 	Module class: X.Org Video Driver
[    21.936] 	ABI class: X.Org Video Driver, version 20.0
[    21.936] (II) FBTURBO: driver for framebuffer: fbturbo
[    21.990] (WW) Falling back to old probe method for fbturbo
[    21.990] (II) Loading sub module "fbdevhw"
[    21.990] (II) LoadModule: "fbdevhw"
[    21.990] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    21.998] (II) Module fbdevhw: vendor="X.Org Foundation"
[    21.998] 	compiled for 1.18.4, module version = 0.0.2
[    21.998] 	ABI class: X.Org Video Driver, version 20.0
[    21.998] (II) FBTURBO(0): using /dev/fb0
[    21.998] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[    21.998] (II) FBTURBO(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[    21.998] (==) FBTURBO(0): Depth 24, (==) framebuffer bpp 32
[    21.998] (==) FBTURBO(0): RGB weight 888
[    21.999] (==) FBTURBO(0): Default visual is TrueColor
[    21.999] (==) FBTURBO(0): Using gamma correction (1.0, 1.0, 1.0)
[    21.999] (II) FBTURBO(0): hardware:  (video memory: 16200kB)
[    21.999] (**) FBTURBO(0): Option "fbdev" "/dev/fb0"
[    21.999] (**) FBTURBO(0): Option "SwapbuffersWait" "true"
[    21.999] (II) FBTURBO(0): processor: Unknown
[    21.999] (II) FBTURBO(0): checking modes against framebuffer device...
[    21.999] (II) FBTURBO(0): checking modes against monitor...
[    21.999] (--) FBTURBO(0): Virtual size is 1920x1080 (pitch 1920)
[    21.999] (**) FBTURBO(0):  Built-in mode "current"
[    21.999] (==) FBTURBO(0): DPI set to (96, 96)
[    21.999] (II) Loading sub module "fb"
[    21.999] (II) LoadModule: "fb"
[    22.000] (II) Loading /usr/lib/xorg/modules/libfb.so
[    22.008] (II) Module fb: vendor="X.Org Foundation"
[    22.008] 	compiled for 1.18.4, module version = 1.0.0
[    22.008] 	ABI class: X.Org ANSI C Emulation, version 0.4
[    22.008] (**) FBTURBO(0): using shadow framebuffer
[    22.008] (II) Loading sub module "shadow"
[    22.008] (II) LoadModule: "shadow"
[    22.008] (II) Loading /usr/lib/xorg/modules/libshadow.so
[    22.012] (II) Module shadow: vendor="X.Org Foundation"
[    22.012] 	compiled for 1.18.4, module version = 1.1.0
[    22.012] 	ABI class: X.Org ANSI C Emulation, version 0.4
[    22.012] (==) Depth 24 pixmap format is 32 bpp
[    22.058] (II) FBTURBO(0): can't load 'g2d_23' kernel module
[    22.058] (II) FBTURBO(0): failed to enable the use of sunxi display controller
[    22.058] (II) FBTURBO(0): No sunxi-g2d hardware detected (check /dev/disp and /dev/g2d)
[    22.058] (II) FBTURBO(0): G2D hardware acceleration can't be enabled
[    22.062] (==) FBTURBO(0): Backing store enabled
[    22.068] (==) FBTURBO(0): DPMS enabled
[    22.068] (II) FBTURBO(0): failed to enable hardware cursor
[    22.073] (II) FBTURBO(0): can't load 'mali' kernel module
[    22.078] (II) FBTURBO(0): can't load 'mali_drm' kernel module
[    22.083] (II) FBTURBO(0): can't load 'sunxi_cedar_mod' kernel module
[    22.083] (II) Loading sub module "dri2"
[    22.083] (II) LoadModule: "dri2"
[    22.083] (II) Module "dri2" already built-in
[    22.154] SunxiMaliDRI2_Init: drmOpen failed!
[    22.155] (II) FBTURBO(0): failed to enable DRI2 integration for Mali GPU
[    22.156] (==) RandR enabled
[    22.177] (II) SELinux: Disabled on system
[    22.180] (II) AIGLX: Screen 0 is not DRI2 capable
[    22.180] (EE) AIGLX: reverting to software rendering
[    23.830] (II) AIGLX: enabled GLX_MESA_copy_sub_buffer
[    23.832] (II) AIGLX: Loaded and initialized swrast
[    23.833] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[    24.077] (II) config/udev: Adding input device axp81x-supplyer (/dev/input/event0)
[    24.078] (**) axp81x-supplyer: Applying InputClass "evdev keyboard catchall"
[    24.078] (II) LoadModule: "evdev"
[    24.078] (II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[    24.093] (II) Module evdev: vendor="X.Org Foundation"
[    24.093] 	compiled for 1.18.1, module version = 2.10.1
[    24.093] 	Module class: X.Org XInput Driver
[    24.093] 	ABI class: X.Org XInput driver, version 22.1
[    24.093] (II) Using input driver 'evdev' for 'axp81x-supplyer'
[    24.093] (**) axp81x-supplyer: always reports core events
[    24.093] (**) evdev: axp81x-supplyer: Device: "/dev/input/event0"
[    24.093] (--) evdev: axp81x-supplyer: Vendor 0x1 Product 0x1
[    24.093] (--) evdev: axp81x-supplyer: Found keys
[    24.094] (II) evdev: axp81x-supplyer: Configuring as keyboard
[    24.094] (**) Option "config_info" "udev:/sys/devices/platform/axp81x_board/axp81x-supplyer.47/input/input0/event0"
[    24.094] (II) XINPUT: Adding extended input device "axp81x-supplyer" (type: KEYBOARD, id 6)
[    24.094] (**) Option "xkb_rules" "evdev"
[    24.094] (**) Option "xkb_model" "pc101"
[    24.094] (**) Option "xkb_layout" "us"
[    24.094] (**) Option "xkb_options" "lv3:ralt_switch"
[    24.170] (II) config/udev: Adding input device USB Optical Mouse (/dev/input/event1)
[    24.170] (**) USB Optical Mouse: Applying InputClass "evdev pointer catchall"
[    24.170] (II) Using input driver 'evdev' for 'USB Optical Mouse'
[    24.170] (**) USB Optical Mouse: always reports core events
[    24.170] (**) evdev: USB Optical Mouse: Device: "/dev/input/event1"
[    24.170] (--) evdev: USB Optical Mouse: Vendor 0x1bcf Product 0x7
[    24.170] (--) evdev: USB Optical Mouse: Found 3 mouse buttons
[    24.170] (--) evdev: USB Optical Mouse: Found scroll wheel(s)
[    24.170] (--) evdev: USB Optical Mouse: Found relative axes
[    24.170] (--) evdev: USB Optical Mouse: Found x and y relative axes
[    24.171] (--) evdev: USB Optical Mouse: Found absolute axes
[    24.171] (II) evdev: USB Optical Mouse: Forcing absolute x/y axes to exist.
[    24.171] (II) evdev: USB Optical Mouse: Configuring as mouse
[    24.171] (II) evdev: USB Optical Mouse: Adding scrollwheel support
[    24.171] (**) evdev: USB Optical Mouse: YAxisMapping: buttons 4 and 5
[    24.171] (**) evdev: USB Optical Mouse: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    24.171] (**) Option "config_info" "udev:/sys/devices/soc.0/1c1b000.ehci1-controller/usb1/1-1/1-1.2/1-1.2:1.0/input/input1/event1"
[    24.171] (II) XINPUT: Adding extended input device "USB Optical Mouse" (type: MOUSE, id 7)
[    24.171] (II) evdev: USB Optical Mouse: initialized for relative axes.
[    24.171] (WW) evdev: USB Optical Mouse: ignoring absolute axes.
[    24.172] (**) USB Optical Mouse: (accel) keeping acceleration scheme 1
[    24.172] (**) USB Optical Mouse: (accel) acceleration profile 0
[    24.172] (**) USB Optical Mouse: (accel) acceleration factor: 2.000
[    24.172] (**) USB Optical Mouse: (accel) acceleration threshold: 4
[    24.173] (II) config/udev: Adding input device USB Optical Mouse (/dev/input/mouse0)
[    24.174] (II) No input driver specified, ignoring this device.
[    24.174] (II) This device may have been added with another device file.
[    24.175] (II) config/udev: Adding input device SIGMACHIP USB Keyboard (/dev/input/event2)
[    24.175] (**) SIGMACHIP USB Keyboard: Applying InputClass "evdev keyboard catchall"
[    24.175] (II) Using input driver 'evdev' for 'SIGMACHIP USB Keyboard'
[    24.175] (**) SIGMACHIP USB Keyboard: always reports core events
[    24.176] (**) evdev: SIGMACHIP USB Keyboard: Device: "/dev/input/event2"
[    24.176] (--) evdev: SIGMACHIP USB Keyboard: Vendor 0x1c4f Product 0x2
[    24.176] (--) evdev: SIGMACHIP USB Keyboard: Found keys
[    24.176] (II) evdev: SIGMACHIP USB Keyboard: Configuring as keyboard
[    24.176] (**) Option "config_info" "udev:/sys/devices/soc.0/1c1b000.ehci1-controller/usb1/1-1/1-1.4/1-1.4:1.0/input/input2/event2"
[    24.176] (II) XINPUT: Adding extended input device "SIGMACHIP USB Keyboard" (type: KEYBOARD, id 8)
[    24.176] (**) Option "xkb_rules" "evdev"
[    24.176] (**) Option "xkb_model" "pc101"
[    24.176] (**) Option "xkb_layout" "us"
[    24.176] (**) Option "xkb_options" "lv3:ralt_switch"
[    24.179] (II) config/udev: Adding input device SIGMACHIP USB Keyboard (/dev/input/event3)
[    24.179] (**) SIGMACHIP USB Keyboard: Applying InputClass "evdev keyboard catchall"
[    24.179] (II) Using input driver 'evdev' for 'SIGMACHIP USB Keyboard'
[    24.179] (**) SIGMACHIP USB Keyboard: always reports core events
[    24.179] (**) evdev: SIGMACHIP USB Keyboard: Device: "/dev/input/event3"
[    24.179] (--) evdev: SIGMACHIP USB Keyboard: Vendor 0x1c4f Product 0x2
[    24.179] (--) evdev: SIGMACHIP USB Keyboard: Found 1 mouse buttons
[    24.179] (--) evdev: SIGMACHIP USB Keyboard: Found scroll wheel(s)
[    24.179] (--) evdev: SIGMACHIP USB Keyboard: Found relative axes
[    24.179] (II) evdev: SIGMACHIP USB Keyboard: Forcing relative x/y axes to exist.
[    24.179] (--) evdev: SIGMACHIP USB Keyboard: Found absolute axes
[    24.179] (II) evdev: SIGMACHIP USB Keyboard: Forcing absolute x/y axes to exist.
[    24.179] (--) evdev: SIGMACHIP USB Keyboard: Found keys
[    24.179] (II) evdev: SIGMACHIP USB Keyboard: Configuring as mouse
[    24.179] (II) evdev: SIGMACHIP USB Keyboard: Configuring as keyboard
[    24.179] (II) evdev: SIGMACHIP USB Keyboard: Adding scrollwheel support
[    24.180] (**) evdev: SIGMACHIP USB Keyboard: YAxisMapping: buttons 4 and 5
[    24.180] (**) evdev: SIGMACHIP USB Keyboard: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    24.180] (**) Option "config_info" "udev:/sys/devices/soc.0/1c1b000.ehci1-controller/usb1/1-1/1-1.4/1-1.4:1.1/input/input3/event3"
[    24.180] (II) XINPUT: Adding extended input device "SIGMACHIP USB Keyboard" (type: KEYBOARD, id 9)
[    24.180] (**) Option "xkb_rules" "evdev"
[    24.180] (**) Option "xkb_model" "pc101"
[    24.180] (**) Option "xkb_layout" "us"
[    24.180] (**) Option "xkb_options" "lv3:ralt_switch"
[    24.180] (II) evdev: SIGMACHIP USB Keyboard: initialized for relative axes.
[    24.181] (WW) evdev: SIGMACHIP USB Keyboard: ignoring absolute axes.
[    24.181] (**) SIGMACHIP USB Keyboard: (accel) keeping acceleration scheme 1
[    24.181] (**) SIGMACHIP USB Keyboard: (accel) acceleration profile 0
[    24.181] (**) SIGMACHIP USB Keyboard: (accel) acceleration factor: 2.000
[    24.181] (**) SIGMACHIP USB Keyboard: (accel) acceleration threshold: 4
[    24.184] (II) config/udev: Adding input device sunxi_ir_recv (/dev/input/event5)
[    24.184] (**) sunxi_ir_recv: Applying InputClass "evdev keyboard catchall"
[    24.184] (II) Using input driver 'evdev' for 'sunxi_ir_recv'
[    24.184] (**) sunxi_ir_recv: always reports core events
[    24.184] (**) evdev: sunxi_ir_recv: Device: "/dev/input/event5"
[    24.184] (--) evdev: sunxi_ir_recv: Vendor 0x1 Product 0x1
[    24.184] (--) evdev: sunxi_ir_recv: Found keys
[    24.184] (II) evdev: sunxi_ir_recv: Configuring as keyboard
[    24.184] (**) Option "config_info" "udev:/sys/devices/soc.0/1f02000.s_cir/rc/rc0/input5/event5"
[    24.184] (II) XINPUT: Adding extended input device "sunxi_ir_recv" (type: KEYBOARD, id 10)
[    24.184] (**) Option "xkb_rules" "evdev"
[    24.184] (**) Option "xkb_model" "pc101"
[    24.184] (**) Option "xkb_layout" "us"
[    24.184] (**) Option "xkb_options" "lv3:ralt_switch"
[    24.186] (II) config/udev: Adding input device sunxi-ths (/dev/input/event4)
[    24.186] (II) No input driver specified, ignoring this device.
[    24.186] (II) This device may have been added with another device file.
[    24.187] (II) config/udev: Adding input device MCE IR Keyboard/Mouse (sunxi-rc-recv) (/dev/input/event6)
[    24.187] (**) MCE IR Keyboard/Mouse (sunxi-rc-recv): Applying InputClass "evdev pointer catchall"
[    24.187] (**) MCE IR Keyboard/Mouse (sunxi-rc-recv): Applying InputClass "evdev keyboard catchall"
[    24.187] (II) Using input driver 'evdev' for 'MCE IR Keyboard/Mouse (sunxi-rc-recv)'
[    24.187] (**) MCE IR Keyboard/Mouse (sunxi-rc-recv): always reports core events
[    24.187] (**) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Device: "/dev/input/event6"
[    24.188] (--) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Vendor 0 Product 0
[    24.188] (--) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Found 3 mouse buttons
[    24.188] (--) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Found relative axes
[    24.188] (--) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Found x and y relative axes
[    24.188] (--) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Found keys
[    24.188] (II) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Configuring as mouse
[    24.188] (II) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Configuring as keyboard
[    24.188] (**) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): YAxisMapping: buttons 4 and 5
[    24.188] (**) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    24.188] (**) Option "config_info" "udev:/sys/devices/virtual/input/input6/event6"
[    24.188] (II) XINPUT: Adding extended input device "MCE IR Keyboard/Mouse (sunxi-rc-recv)" (type: KEYBOARD, id 11)
[    24.188] (**) Option "xkb_rules" "evdev"
[    24.188] (**) Option "xkb_model" "pc101"
[    24.188] (**) Option "xkb_layout" "us"
[    24.188] (**) Option "xkb_options" "lv3:ralt_switch"
[    24.189] (II) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): initialized for relative axes.
[    24.189] (**) MCE IR Keyboard/Mouse (sunxi-rc-recv): (accel) keeping acceleration scheme 1
[    24.189] (**) MCE IR Keyboard/Mouse (sunxi-rc-recv): (accel) acceleration profile 0
[    24.189] (**) MCE IR Keyboard/Mouse (sunxi-rc-recv): (accel) acceleration factor: 2.000
[    24.189] (**) MCE IR Keyboard/Mouse (sunxi-rc-recv): (accel) acceleration threshold: 4
[    24.190] (II) config/udev: Adding input device MCE IR Keyboard/Mouse (sunxi-rc-recv) (/dev/input/mouse1)
[    24.190] (II) No input driver specified, ignoring this device.
[    24.190] (II) This device may have been added with another device file.
[  9042.621] (II) evdev: MCE IR Keyboard/Mouse (sunxi-rc-recv): Close
[  9042.622] (II) UnloadModule: "evdev"
[  9042.622] (II) evdev: sunxi_ir_recv: Close
[  9042.622] (II) UnloadModule: "evdev"
[  9042.622] (II) evdev: SIGMACHIP USB Keyboard: Close
[  9042.622] (II) UnloadModule: "evdev"
[  9042.622] (II) evdev: SIGMACHIP USB Keyboard: Close
[  9042.622] (II) UnloadModule: "evdev"
[  9042.622] (II) evdev: USB Optical Mouse: Close
[  9042.622] (II) UnloadModule: "evdev"
[  9042.622] (II) evdev: axp81x-supplyer: Close
[  9042.622] (II) UnloadModule: "evdev"
[  9042.658] (II) Server terminated successfully (0). Closing log file.

**Comment by avafinger** [comment]
Things get interesting, this page alloc warning does not mean memory allocation failed, as discussed here:
https://patchwork.kernel.org/patch/5218461/

I don't see many people praising decoding on A64 is really working but i don't see anyone complaining.

**Comment by avafinger** [comment]
After reading this: https://chengyihe.wordpress.com/2015/08/11/kernel-mm-cma-allocation-failure-1/
i have to review the mm kernel code.
My kernel code is deviated from longsleep's kernel, i will run with older kernel and check if the issue is at my side. I leave it open till i check mm kernel code.

**Comment by avafinger** [comment]
The culprit is audio, playing video without audio gets smooth video. The ION memory error is indeed a warning and harmless but is annoying, kernel should be patched.  Works with cma=64 MB.
No need for FBTURBO or UMP, not even xorg.conf.
