### ISSUE TITLE
Fedora23 make error

### ISSUE THREAD

**Issue by yueyihua** [linux-sunxi/libvdpau-sunxi#59]
cc -c tiled_yuv.S -o tiled_yuv.o
tiled_yuv.S: Assembler messages:
tiled_yuv.S:25: Error: unknown pseudo-op: `.syntax'
tiled_yuv.S:26: Error: no such architecture: `armv7'
tiled_yuv.S:26: Error: junk at end of line, first unrecognized character is `-'
tiled_yuv.S:27: Error: unknown pseudo-op: `.fpu'
tiled_yuv.S:28: Error: unknown pseudo-op: `.thumb'
tiled_yuv.S:46: Error: no such instruction: `src .req r0'
tiled_yuv.S:47: Error: no such instruction: `dst .req r1'
tiled_yuv.S:48: Error: no such instruction: `pitch .req r2'
tiled_yuv.S:49: Error: no such instruction: `cnt .req r3'
tiled_yuv.S:50: Error: no such instruction: `tline .req r4'
tiled_yuv.S:51: Error: no such instruction: `height .req r5'
tiled_yuv.S:52: Error: no such instruction: `rest .req r6'
tiled_yuv.S:53: Error: no such instruction: `ntiles .req r7'
tiled_yuv.S:54: Error: no such instruction: `tmpsrc .req r8'
tiled_yuv.S:55: Error: no such instruction: `dst2 .req r9'
tiled_yuv.S:56: Error: no such instruction: `tsize .req r12'
tiled_yuv.S:57: Error: no such instruction: `nextlin .req lr'
tiled_yuv.S:59: Error: unknown pseudo-op: `.thumb_func'
tiled_yuv.S:60: Error: invalid char '{' beginning operand 1 `{r4'
tiled_yuv.S:61: Error: no such instruction: `ldr HEIGHT,[sp,'
tiled_yuv.S:62: Error: too many memory references for `add'
tiled_yuv.S:63: Error: no such instruction: `lsrs NTILES,r3,'
tiled_yuv.S:64: Error: no such instruction: `bic NEXTLIN,NEXTLIN,'
tiled_yuv.S:65: Error: too many memory references for `and'
tiled_yuv.S:66: Error: too many memory references for `lsl'
tiled_yuv.S:67: Error: too many memory references for `sub'
tiled_yuv.S:68: Warning: `TLINE' is not valid here (expected `(%rsi)')
tiled_yuv.S:68: Error: expecting operand after ','; got nothing
tiled_yuv.S:69: Error: no such instruction: `rsb NEXTLIN,NEXTLIN,'
tiled_yuv.S:70: Error: expecting operand after ','; got nothing
tiled_yuv.S:73: Error: no such instruction: `cbz NTILES,3f'
tiled_yuv.S:74: Error: too many memory references for `mov'
tiled_yuv.S:77: Error: no such instruction: `pld [SRC,TSIZE]'
tiled_yuv.S:78: Error: no such instruction: `vld1.8 {d0 - d3},[SRC:256],TSIZE'
tiled_yuv.S:79: Error: expecting operand after ','; got nothing
tiled_yuv.S:80: Error: no such instruction: `vst1.8 {d0 - d3},[DST]!'
tiled_yuv.S:81: Error: no such instruction: `bne 2b'
tiled_yuv.S:83: Error: no such instruction: `cbnz REST,4f'
tiled_yuv.S:86: Error: too many memory references for `add'
tiled_yuv.S:89: Error: expecting operand after ','; got nothing
tiled_yuv.S:90: Error: no such instruction: `itee ne'
tiled_yuv.S:91: Error: no such instruction: `addne SRC,NEXTLIN'
tiled_yuv.S:92: Error: no such instruction: `subeq SRC,'
tiled_yuv.S:93: Error: no such instruction: `moveq TLINE,'
tiled_yuv.S:95: Error: expecting operand after ','; got nothing
tiled_yuv.S:96: Error: no such instruction: `bne 1b'
tiled_yuv.S:97: Error: invalid char '{' beginning operand 1 `{r4'
tiled_yuv.S:100: Error: too many memory references for `mov'
tiled_yuv.S:101: Error: no such instruction: `tst REST,'
tiled_yuv.S:102: Error: no such instruction: `beq 5f'
tiled_yuv.S:103: Error: no such instruction: `vld1.8 {d0 - d1},[TMPSRC:128]!'
tiled_yuv.S:104: Error: no such instruction: `vst1.8 {d0 - d1},[DST]!'
tiled_yuv.S:105: Error: too many memory references for `add'
tiled_yuv.S:106: Error: too many memory references for `and'
tiled_yuv.S:107: Error: no such instruction: `beq 7b'
tiled_yuv.S:108: Error: no such instruction: `vld1.8 {d0[0]},[TMPSRC]!'
tiled_yuv.S:109: Error: expecting operand after ','; got nothing
tiled_yuv.S:110: Error: no such instruction: `vst1.8 {d0[0]},[DST]!'
tiled_yuv.S:111: Error: no such instruction: `bne 6b'
tiled_yuv.S:112: Error: no such instruction: `b 7b'
tiled_yuv.S:115: Error: unknown pseudo-op: `.thumb_func'
tiled_yuv.S:116: Error: invalid char '{' beginning operand 1 `{r4'
tiled_yuv.S:117: Error: too many memory references for `mov'
tiled_yuv.S:118: Error: no such instruction: `ldr HEIGHT,[sp,'
tiled_yuv.S:119: Error: no such instruction: `ldr r4,[sp,'
tiled_yuv.S:120: Error: too many memory references for `add'
tiled_yuv.S:121: Error: no such instruction: `lsrs NTILES,r4,'
tiled_yuv.S:122: Error: no such instruction: `bic NEXTLIN,NEXTLIN,'
tiled_yuv.S:123: Error: no such instruction: `ubfx REST,r4,'
tiled_yuv.S:124: Error: too many memory references for `lsl'
tiled_yuv.S:125: Error: too many memory references for `sub'
tiled_yuv.S:126: Warning: `TLINE' is not valid here (expected `(%rsi)')
tiled_yuv.S:126: Error: expecting operand after ','; got nothing
tiled_yuv.S:127: Error: no such instruction: `rsb NEXTLIN,NEXTLIN,'
tiled_yuv.S:128: Error: expecting operand after ','; got nothing
tiled_yuv.S:131: Error: no such instruction: `cbz NTILES,3f'
tiled_yuv.S:132: Error: too many memory references for `mov'
tiled_yuv.S:135: Error: no such instruction: `pld [SRC,TSIZE]'
tiled_yuv.S:136: Error: no such instruction: `vld2.8 {d0 - d3},[SRC:256],TSIZE'
tiled_yuv.S:137: Error: expecting operand after ','; got nothing
tiled_yuv.S:138: Error: no such instruction: `vst1.8 {d0 - d1},[DST]!'
tiled_yuv.S:139: Error: no such instruction: `vst1.8 {d2 - d3},[DST2]!'
tiled_yuv.S:140: Error: no such instruction: `bne 2b'
tiled_yuv.S:142: Error: no such instruction: `cbnz REST,4f'
tiled_yuv.S:145: Error: too many memory references for `add'
tiled_yuv.S:146: Error: too many memory references for `add'
tiled_yuv.S:149: Error: expecting operand after ','; got nothing
tiled_yuv.S:150: Error: no such instruction: `itee ne'
tiled_yuv.S:151: Error: no such instruction: `addne SRC,NEXTLIN'
tiled_yuv.S:152: Error: no such instruction: `subeq SRC,'
tiled_yuv.S:153: Error: no such instruction: `moveq TLINE,'
tiled_yuv.S:155: Error: expecting operand after ','; got nothing
tiled_yuv.S:156: Error: no such instruction: `bne 1b'
tiled_yuv.S:157: Error: invalid char '{' beginning operand 1 `{r4'
tiled_yuv.S:160: Error: too many memory references for `mov'
tiled_yuv.S:161: Error: no such instruction: `tst REST,'
tiled_yuv.S:162: Error: no such instruction: `beq 5f'
tiled_yuv.S:163: Error: no such instruction: `vld2.8 {d0 - d1},[TMPSRC:128]!'
tiled_yuv.S:164: Error: no such instruction: `vst1.8 {d0},[DST]!'
tiled_yuv.S:165: Error: no such instruction: `vst1.8 {d1},[DST2]!'
tiled_yuv.S:166: Error: too many memory references for `add'
tiled_yuv.S:167: Error: too many memory references for `and'
tiled_yuv.S:168: Error: no such instruction: `beq 7b'
tiled_yuv.S:169: Error: no such instruction: `vld2.8 {d0[0],d1[0]},[TMPSRC]!'
tiled_yuv.S:170: Error: expecting operand after ','; got nothing
tiled_yuv.S:171: Error: no such instruction: `vst1.8 {d0[0]},[DST]!'
tiled_yuv.S:172: Error: no such instruction: `vst1.8 {d1[0]},[DST2]!'
tiled_yuv.S:173: Error: no such instruction: `bne 6b'
tiled_yuv.S:174: Error: no such instruction: `b 7b'
Makefile:47: recipe for target 'tiled_yuv.o' failed
make: *** [tiled_yuv.o] Error 1

**Comment by rellla** [comment]
Do you build on an ARM host respectively cross-build for ARM destination?

**Comment by yueyihua** [comment]
@rellla 

Not ARM, but Intel x86_64 platform.

# uname -a
Linux  4.8.13-100.fc23.x86_64 #1 SMP Fri Dec 9 14:51:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
# uname -r
4.8.13-100.fc23.x86_64
# cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Celeron(R) CPU 1037U @ 1.80GHz
stepping	: 9
microcode	: 0x17
cpu MHz		: 1786.157
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts
bugs		:
bogomips	: 3599.85
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Celeron(R) CPU 1037U @ 1.80GHz
stepping	: 9
microcode	: 0x17
cpu MHz		: 1800.000
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts
bugs		:
bogomips	: 3603.62
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

**Comment by rellla** [comment]
tiled_yuv.S is Arm specific code, which will only compile on or for ARM platforms. Compiling on i386 as the host system without setting up a proper cross-compile environment will not work. Try to compile it on ARM.
